In [ ]:
import numpy as np

# Define system matrices
A = np.array([[-5, 1], [3, -5]])
B = np.array([[0.5], [1]])
C = np.eye(2)


from scipy.linalg import solve_continuous_are

def lqr(A, B, Q, R):
    """
    Solve the continuous-time LQR controller.

    Args:
    - A: system matrix
    - B: input matrix
    - Q: state cost matrix
    - R: input cost matrix

    Returns:
    - K: LQR gain matrix
    """
    # Solve the continuous-time algebraic Riccati equation (CARE)
    P = solve_continuous_are(A, B, Q, R)

    # LQR gain matrix
    K = np.dot(np.linalg.inv(R), np.dot(B.T, P))

    return -K  # Return negative K for stabilization

# Define Q and R for LQR
Q = np.eye(2)
R = np.array([[1]])

# Calculate LQR gain
K_lqr = lqr(A, B, Q, R)
# K_lqr = np.array([[-0.3740,   -0.3916]])
# K_lqr = np.array([[-0.2,   -1]])


# Print LQR gain
print("The LQR gain (-K) is:")
print(K_lqr)

# # Check condition 1
# cond1 = A + np.dot(np.dot(B, np.array([[s11, s12]])), C)
# print("The following matrix should be Metzler")
# print(cond1)

# # Check condition 2
# cond2 = A + np.dot(np.dot(B, np.array([[s21, s22]])), C)
# print("The following matrix should be Hurwitz")
# print(cond2)
# print("The eigenvalues are:")
# print(np.linalg.eigvals(cond2))
# print("The Characteristic Polynomial is:")
# print(np.poly(cond2))

# Check selected gain
selected_gain = A + np.dot(B, K_lqr)
print("This matrix should be Metzler (This is for selected gain)")
print(selected_gain)
print("The eigenvalues should be negative (This is for selected gain)")
print(np.linalg.eigvals(selected_gain))

# Generating data to train NN
num_vectors = 500
vector4 = np.random.rand(num_vectors, 2) * 0.01
vector3 = np.random.rand(num_vectors, 2) * 0.1
vector2 = np.random.rand(num_vectors, 2) * 1
vector1 = np.random.rand(num_vectors, 2) * 10

vector = np.vstack((vector1, vector2, vector3, vector4))
np.random.shuffle(vector)

# Calculate target data
u = np.dot(vector, K_lqr.T)

# Save data to text files
xs = vector
us = u

The LQR gain (-K) is:
[[-0.10562857 -0.12860043]]
This matrix should be Metzler (This is for selected gain)
[[-5.05281428  0.93569979]
 [ 2.89437143 -5.12860043]]
The eigenvalues should be negative (This is for selected gain)
[-3.44459113 -6.73682358]


In [ ]:
# ## n = 3
# import numpy as np

# # Define system matrices
# A = np.array([[-5, 1, 1], [3, -5, 1], [1, 1, -5]])
# B = np.array([[0.5], [1], [1]])
# C = np.eye(3)

# from scipy.linalg import solve_continuous_are

# def lqr(A, B, Q, R):
#     """
#     Solve the continuous-time LQR controller.

#     Args:
#     - A: system matrix
#     - B: input matrix
#     - Q: state cost matrix
#     - R: input cost matrix

#     Returns:
#     - K: LQR gain matrix
#     """
#     # Solve the continuous-time algebraic Riccati equation (CARE)
#     P = solve_continuous_are(A, B, Q, R)

#     # LQR gain matrix
#     K = np.dot(np.linalg.inv(R), np.dot(B.T, P))

#     return -K  # Return negative K for stabilization

# # Define Q and R for LQR
# Q = np.eye(3)
# R = np.array([[1]])

# # Calculate LQR gain
# K_lqr = lqr(A, B, Q, R)
# # K_lqr = np.array([[ -0.02504158, -0.0764221]])


# # Print LQR gain
# print("The LQR gain (-K) is:")
# print(K_lqr)

# # # Check condition 1
# # cond1 = A + np.dot(np.dot(B, np.array([[s11, s12]])), C)
# # print("The following matrix should be Metzler")
# # print(cond1)

# # # Check condition 2
# # cond2 = A + np.dot(np.dot(B, np.array([[s21, s22]])), C)
# # print("The following matrix should be Hurwitz")
# # print(cond2)
# # print("The eigenvalues are:")
# # print(np.linalg.eigvals(cond2))
# # print("The Characteristic Polynomial is:")
# # print(np.poly(cond2))

# # Check selected gain
# selected_gain = A + np.dot(B, K_lqr)
# print("This matrix should be Metzler (This is for selected gain)")
# print(selected_gain)
# print("The eigenvalues should be negative (This is for selected gain)")
# print(np.linalg.eigvals(selected_gain))

# # Generating data to train NN
# num_vectors = 500
# vector4 = np.random.rand(num_vectors, 3) * 0.01
# vector3 = np.random.rand(num_vectors, 3) * 0.1
# vector2 = np.random.rand(num_vectors, 3) * 1
# vector1 = np.random.rand(num_vectors, 3) * 10

# vector = np.vstack((vector1, vector2, vector3, vector4))
# np.random.shuffle(vector)

# # Calculate target data
# u = np.dot(vector, K_lqr.T)

# # Save data to text files
# xs = vector
# us = u

# import pandas as pd
# import numpy as np
# import tensorflow as tf
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.constraints import Constraint
# from tensorflow.keras.callbacks import EarlyStopping
# from sklearn.metrics import r2_score
# import keras
# from keras import layers


# # Custom constraint for weight normalization between -1 and 1
# class WeightNormalization(tf.keras.constraints.Constraint):
#     def __init__(self, min_value=-1, max_value=1):
#         self.min_value = min_value
#         self.max_value = max_value

#     def __call__(self, w):
#         w = tf.cast(w, tf.float32)
#         w = tf.where(w < self.min_value, self.min_value * tf.ones_like(w), w)
#         w = tf.where(w > self.max_value, self.max_value * tf.ones_like(w), w)
#         return w

# # Define neural network architecture
# model = Sequential()
# model.add(Dense(10, input_dim=3, activation='tanh', use_bias=False, name='W1', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))
# model.add(Dense(10, input_dim=10, activation='tanh', use_bias=False, name='W2', kernel_constraint=WeightNormalization(min_value=-.3, max_value=.3)))
# # model.add(Dense(5, input_dim=5, activation='tanh', use_bias=False, name='W3', kernel_constraint=WeightNormalization(min_value=-.3, max_value=.3)))
# model.add(Dense(1, use_bias=False, name='W3', kernel_constraint=WeightNormalization(min_value=-.3, max_value=.3)))

# opt = keras.optimizers.Adam(learning_rate=0.001)

# # Compile the model
# model.compile(optimizer=opt, loss='mse')

# # Train the model
# epochs = 150
# batch_size = 32
# verbose = True
# validation_split = 0.0
# early = EarlyStopping(monitor='loss', min_delta=0.001, patience=10, verbose=1, restore_best_weights=True)

# model.fit(xs, us, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)

# # Evaluate the model
# pred = model.predict(xs)
# r2 = r2_score(us, pred)
# print("R-squared:", r2)

# # Save the transpose of the weights to CSV files
# for layer in model.layers:
#     layer_name = layer.name
#     weights_transpose = np.transpose(layer.get_weights()[0])
#     df = pd.DataFrame(weights_transpose, columns=[f'{layer_name}_{i}' for i in range(weights_transpose.shape[1])])
#     df.to_csv(f'{layer_name}.csv', index=False, header=False)

#     print(f"Transpose of weights for layer {layer_name} saved to {layer_name}.csv")

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.constraints import Constraint
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import r2_score
import keras
from keras import layers

# Custom constraint for weight normalization between -1 and 1
class WeightNormalization(tf.keras.constraints.Constraint):
    def __init__(self, min_value=-1, max_value=1):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, w):
        w = tf.cast(w, tf.float32)
        w = tf.where(w < self.min_value, self.min_value * tf.ones_like(w), w)
        w = tf.where(w > self.max_value, self.max_value * tf.ones_like(w), w)
        return w

# Define neural network architecture
model = Sequential()
model.add(Dense(10, input_dim=2, activation='tanh', use_bias=False, name='W1', kernel_constraint=WeightNormalization(min_value=-1, max_value=1)))
model.add(Dense(10, input_dim=10, activation='tanh', use_bias=False, name='W2', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))
# model.add(Dense(15, input_dim=15, activation='tanh', use_bias=False, name='W3'))
# model.add(Dense(10, input_dim=15, activation='tanh', use_bias=False, name='W4'))
model.add(Dense(1, use_bias=False, name='W3', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))


opt = keras.optimizers.Adam(learning_rate=0.001)

# Compile the model
model.compile(optimizer=opt, loss='mse')
# normalize_weights_tf(model)

# Train the model
epochs = 150
batch_size = 32
verbose = True
validation_split = 0.0
early = EarlyStopping(monitor = 'loss', min_delta=0.001, patience=10, verbose=1, restore_best_weights=True)

model.fit(xs, us, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)

# Evaluate the model
pred = model.predict(xs)
r2 = r2_score(us, pred)
print("R-squared:", r2)

# Save the transpose of the weights to CSV files
for layer in model.layers:
    layer_name = layer.name
    weights_transpose = np.transpose(layer.get_weights()[0])
    df = pd.DataFrame(weights_transpose, columns=[f'{layer_name}_{i}' for i in range(weights_transpose.shape[1])])
    df.to_csv(f'{layer_name}.csv', index=False, header=False)

    print(f"Transpose of weights for layer {layer_name} saved to {layer_name}.csv")

Epoch 1/150
63/63 [==============================] - 1s 3ms/step - loss: 3.3338
Epoch 2/150
63/63 [==============================] - 0s 2ms/step - loss: 1.9341
Epoch 3/150
63/63 [==============================] - 0s 2ms/step - loss: 1.3435
Epoch 4/150
63/63 [==============================] - 0s 2ms/step - loss: 1.0632
Epoch 5/150
63/63 [==============================] - 0s 2ms/step - loss: 0.8858
Epoch 6/150
63/63 [==============================] - 0s 2ms/step - loss: 0.7470
Epoch 7/150
63/63 [==============================] - 0s 2ms/step - loss: 0.6327
Epoch 8/150
63/63 [==============================] - 0s 2ms/step - loss: 0.5395
Epoch 9/150
63/63 [==============================] - 0s 2ms/step - loss: 0.4658
Epoch 10/150
63/63 [==============================] - 0s 2ms/step - loss: 0.4116
Epoch 11/150
63/63 [==============================] - 0s 2ms/step - loss: 0.3712
Epoch 12/150
63/63 [==============================] - 0s 2ms/step - loss: 0.3369
Epoch 13/150
63/63 [=================

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.constraints import Constraint
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import r2_score
import keras
from keras import layers


# Custom constraint for weight normalization between -1 and 1
class WeightNormalization(tf.keras.constraints.Constraint):
    def __init__(self, min_value=-1, max_value=1):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, w):
        w = tf.cast(w, tf.float32)
        w = tf.where(w < self.min_value, self.min_value * tf.ones_like(w), w)
        w = tf.where(w > self.max_value, self.max_value * tf.ones_like(w), w)
        return w

# Define neural network architecture
model = Sequential()
model.add(Dense(10, input_dim=2, activation='tanh', use_bias=False, name='W1', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))
model.add(Dense(10, input_dim=10, activation='tanh', use_bias=False, name='W2', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))
model.add(Dense(15, input_dim=15, activation='tanh', use_bias=False, name='W3', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))
model.add(Dense(1, use_bias=False, name='W4', kernel_constraint=WeightNormalization(min_value=-.5, max_value=.5)))

opt = keras.optimizers.Adam(learning_rate=0.001)

# Compile the model
model.compile(optimizer=opt, loss='mse')

# Train the model
epochs = 150
batch_size = 32
verbose = True
validation_split = 0.0
early = EarlyStopping(monitor='loss', min_delta=0.001, patience=10, verbose=1, restore_best_weights=True)

model.fit(xs, us, epochs=epochs, batch_size=batch_size, verbose=verbose, validation_split=validation_split)

# Evaluate the model
pred = model.predict(xs)
r2 = r2_score(us, pred)
print("R-squared:", r2)

# Save the transpose of the weights to CSV files
for layer in model.layers:
    layer_name = layer.name
    weights_transpose = np.transpose(layer.get_weights()[0])
    df = pd.DataFrame(weights_transpose, columns=[f'{layer_name}_{i}' for i in range(weights_transpose.shape[1])])
    df.to_csv(f'{layer_name}.csv', index=False, header=False)

    print(f"Transpose of weights for layer {layer_name} saved to {layer_name}.csv")


In [ ]:
import pandas as pd
import numpy as np
    # Get the weights of each layer
W1 = np.transpose(model.get_layer('W1').get_weights()[0])
W2 = np.transpose(model.get_layer('W2').get_weights()[0])
W3 = np.transpose(model.get_layer('W3').get_weights()[0])
# W4 = np.transpose(model.get_layer('W4').get_weights()[0])
# W5 = np.transpose(model.get_layer('W5').get_weights()[0])


# W1 = pd.read_csv('W1.csv', header=None).values  # Replace 'W1.csv' with the actual filename of W1
# W2 = pd.read_csv('W2.csv', header=None).values  # Replace 'W2.csv' with the actual filename of W2
# W3 = pd.read_csv('W3.csv', header=None).values  # Replace 'W3.csv' with the actual filename of W3
# W4 = pd.read_csv('W4.csv', header=None).values  # Replace 'W3.csv' with the actual filename of W3


# Perform matrix multiplication W3 * W2 * W1
# result_matrix = np.abs(W4) @ np.abs(W3) @ np.abs(W2) @ np.abs(W1)
result_matrix = np.abs(W3) @ np.abs(W2) @ np.abs(W1)

norm_W1 = np.linalg.norm(W1)
norm_W2 = np.linalg.norm(W2)
norm_W3 = np.linalg.norm(W3)
# norm_W4 = np.linalg.norm(W4)
# norm_W5 = np.linalg.norm(W5)

# Multiply the norms together
normws = norm_W1 * norm_W2 * norm_W3
# normws = norm_W1 * norm_W2 * norm_W3 * norm_W4

print("The multiplication of norms:", normws)

# Print the result_matrix or use it as needed
print("Result of multiplication W3 * W2 * W1:")
print(result_matrix)

# # Perform matrix multiplication W3 * W2 * W1
# result_matrix = W3 @ W2 @ W1

# # Print the result_matrix or use it as needed
# print("Result of multiplication W3 * W2 * W1:")
# print(result_matrix)

The multiplication of norms: 3.6251287
Result of multiplication W3 * W2 * W1:
[[1.7913895 1.4389373]]


In [ ]:
# Calculate the matrix A - B * MultipWs * C
metzler_matrix = A - B @ result_matrix @ C

# Print results
print("This matrix should be Metzler (This is for selected gain):")
print(metzler_matrix)

# Check eigenvalues
eigenvalues = np.linalg.eigvals(A + B @ result_matrix @ C)
print("The eigenvalues should be negative (This is for selected gain):")
print(eigenvalues)

This matrix should be Metzler (This is for selected gain):
[[-5.89569473  0.28053135]
 [ 1.20861053 -6.43893731]]
The eigenvalues should be negative (This is for selected gain):
[-6.71581112 -0.94955684]
